### ISSUE TITLE
Should we drop Qt 4.8 compatibility?

### ISSUE THREAD

**Issue by jounathaen** [IJHack/QtPass#152]
In the Github Project description it says, that QtPass requires Qt4.8 or higher. I noticed for example that the code consists of several of QStringLiteral which is - according to https://woboq.com/blog/qstringliteral.html - a QT5 Feature. So maybe the Qt4.8 compatibility should be removed from the project description

**Comment by annejan** [comment]
I have not checked recently but before the 1.0 release for all the Qt5 stuff there was a Qt4 fallback.

I'm giving this a try and if building fails I'll see what we can do, might go either way (updating site / README) or "fixing" the app ;-)

**Comment by annejan** [comment]
Turns out QtPass *was* compatible with Qt4.8 until just now . .

I had travis running a Qt 4.8.1 build since . . forever 

But a very recent change I just literally now merged breaks qt4 compatibility.
https://travis-ci.org/IJHack/qtpass/jobs/105755073

So I'm thinking of dropping Qt4 support since this feature is pretty damn nice and up the dependency to Qt 5.2

Or finding a (neat) work-around . .

**Comment by annejan** [comment]
Might re-open when this comes up again ;)

Will keep (minimal) Qt4.8 compatibility since it is still used a lot in distro's . .

**Comment by annejan** [comment]
I should probably setup CI for 4.8 if we want to keep it on . .
