### ISSUE TITLE
"gpg-agent: command get_passphrase failed: No such file or directory"

### ISSUE THREAD

**Issue by lucaspiller** [IJHack/qtpass#156]
I've been using `pass` for years, and wanted to try out a GUI so here I am.

Whenever I try and decrypt a file I get the following error:

```
gpg-agent[30845]: command get_passphrase failed: No such file or directory
gpg: problem with the agent: No such file or directory
gpg: decryption failed: No secret key
```

If I run `pass <file>` in the terminal it decrypts fine (GPG prompts me for my passphrase each time, it's not stored in the agent or OS X keychain).

I'm running the latest release (v1.1.0). Details of my system:

```
$ which pass
/usr/local/bin/pass
$ which gpg2
/usr/local/bin/gpg2
$ which git
/usr/local/bin/git
$ which pwgen
/usr/local/bin/pwgen
$ uname -a
Darwin Maiz.local 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
```

**Comment by annejan** [comment]
This is caused by pass normally asking for your pinentry (or passphrase) in the console, and there doesn't seem to be a graphical pinentry set in the gpg configuration.

I'm guessing you are running a homebrew version of GPG2?

Unfortunately currently on OSX I have only been able to get QtPass working with https://gpgtools.org/ and their graphical pinentry .

**Comment by passw0rd123** [comment]
@annejan Thanks for your explanation. Installing pinentry-mac on Homebrew worked for me 👍 

    brew install pinentry-mac
    echo "pinentry-program /usr/local/bin/pinentry-mac" >> ~/.gnupg/gpg-agent.conf
