### ISSUE TITLE
Why it's not listed in wikipedia.org/wiki/List_of_password_managers ?

### ISSUE THREAD

**Issue by perpi** [IJHack/qtpass#164]
https://en.wikipedia.org/wiki/List_of_password_managers

It would be great if you update the wiki page for qtpass

**Comment by dromer** [comment]
It's a wiki, you can update it yourself.

**Comment by annejan** [comment]
If/when someone (preferably an established Wikipedian) publishes an article on QtPass I'll be more than willing to add it to that list https://en.wikipedia.org/wiki/QtPass
Just adding an entry doesn't work since they'll be deleted (see https://en.wikipedia.org/w/index.php?title=List_of_password_managers&action=history )

**Comment by annejan** [comment]
https://en.wikipedia.org/wiki/Draft:QtPass

**Comment by annejan** [comment]
@perpi you could help out by editing https://en.wikipedia.org/wiki/Draft:QtPass
