### ISSUE TITLE
When importing settings from 1.1.5 or older clipboard settings revert to No Clipboard

### ISSUE THREAD

**Issue by annejan** [IJHack/QtPass#232]
At-least on linux . .
Probably caused by changes in #224

**Comment by YoshiMan** [comment]
I also think it is fault, because we save integers and no more Strings in den settings. And as fallback there is "no clipboard". 
Maybe we should have a migration process for each release? So we can migrate via code each time there is a release.
I imagin one class for each release. And on startup the version from the settings is checked. Depending on the version some classes are executed, others not.
