### ISSUE TITLE
Unable to locate package (Raspbian) 

### ISSUE THREAD

**Issue by DataBass504** [IJHack/QtPass#287]
I cannot seem to get QTPass too install on Raspbian using the command "**sudo apt-get install qtpass**", it keeps saying "E: Unable to locate package qtpass". I'm a bit new to Linux and raspbian,  can someone please help me out getting it installed properly, I was able to locate it at [http://mirrordirectortest.raspbian.org/raspbian/pool/main/q/qtpass/](url) but when I click on the deb file  & click install I get the following error: Failed to install file.  An unspecified transaction error has occurred. More information is available in the detailed report.

**Comment by jounathaen** [comment]
Installing the deb file will fail, because the file you downloaded is probably th file for desktop clients, which contains binary code that is compiled for the x86 Plattform (mainly Desktop PCs and servers).
As far as I know, there is currently no .deb file for the ARM plattform (used in mobile phones and raspberry & co) because nobody created it yet. I'm not shure and I saw that it is claimed at the QTpass readme, that it is available.

Anyway compiling it yourself by using:
git clone https://github.com/IJHack/QtPass
 qmake && make && make install
"should" work.
But you have to install all the dependencies like qmake, binutils and the qtlibs before

**Comment by jounathaen** [comment]
Ok, I didn't read your question properly, shame on me :-D
Seems that the file you downloaded is indeed for the ARM plattform. Anyway, you could give compiling it yourself a try

**Comment by annejan** [comment]
Is your version of raspbian too old perhaps?

I don't know if there is `sudo apt-get dist-upgrade` for raspbian or some other way to do a major version upgrade..

**Comment by DataBass504** [comment]
@annejan It's not that old of a version, I'm on a few month old pixel version. Although I went ahead and ran the dist-upgrade command in terminal anyway,  few things updated and did a reboot & still nothing when I try to install qtpass.

**Comment by annejan** [comment]
http://archive.raspbian.org/raspbian/pool/main/q/qtpass/
