### ISSUE TITLE
No icons on macOS

### ISSUE THREAD

**Issue by vanyasem** [IJHack/QtPass#377]
I have installed QtPass from brew, no icons are rendered

**Comment by annejan** [comment]
Thanks for creating this issue.

The missing icons and other (button) icon issues have been fixed in https://github.com/IJHack/QtPass/commit/1caf6d74e1cac10ebf3f3264b2d92e122a80fc15, https://github.com/IJHack/QtPass/commit/35ec5a44d39735fb55fd7f69ee7fd408379bd3a9 and https://github.com/IJHack/QtPass/commit/172189b7ae775a6c04a542107e6d08ee86bd15fb and all those improvements will be included in the next release.

I'll close this issue once the new release is out and hooked into the `brew cask` repository.

**Comment by FiloSpaTeam** [comment]
This should be fixed now, right?

**Comment by annejan** [comment]
Yes, fixed in `master` but as I noted above: I'll close this issue once the new release is out and hooked into the brew cask repository.

So I'll keep this issue open for now 😉 
Will probably be able to close in a day or two 😁

**Comment by FiloSpaTeam** [comment]
Yooo :dancer: :dancer:

**Comment by annejan** [comment]
https://github.com/caskroom/homebrew-cask/pull/46803

**Comment by annejan** [comment]
Merged
