### ISSUE TITLE
Renaming passwords and directories fail

### ISSUE THREAD

**Issue by hannes08** [IJHack/QtPass#487]
On renaming of a directory:
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
Git status shows an uncommited but staged change for the folder

On renaming of a file:
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
Git status shows an uncommited but staged change for the file. The file is unencrypted!

**Comment by annejan** [comment]
What OS are you using ?

It would really help if I knew this was a Windows, macOS or Linux thing since all three handle files and folders a bit differently 😉 

Are you using QtPass with "native" gpg support or via `pass`?

Do you have `git` support enables?

**Comment by hannes08** [comment]
Sorry I forgot to mention! :-)

1. OS is Windows 10 (1709)
2. Yes QTPass with "native" gpg
3. Git support is enabled with Automatically push and pull and "add .gpg-id"

On drag and drop of a password the same isse arises (it's moved pyhiscally, staged in git but not committed or pushed). Side note: on moving, all passwords in destination folder will be reencrypted, but these changes are neither staged nor committed nor pushed.

**Comment by schmunk42** [comment]
I had a similar issue ... when renaming password QtPass removes `.gpg` and they disappear from the UI. I have to rename them manually and commit them.

Arch Linux, qtpass 1.3.2

**Comment by jwhonce** [comment]
Same as @schmunk42 using: Fedora 31, qtpass 1.3.2-1.fc31

**Comment by orxobo** [comment]
Getting the same problem as @schmunk42.
Using Ubuntu 18.04 with fresh compile of master as of yesterday.

Also unable to delete a folder and i'm getting:
`fatal: pathspec '/absolutepathtothefoldertodelete/' did not match any files
`
Where absolutepathtothefoldertodelete is the absolute path of the folder to delete, not a literal from the error.

Side note: when compiling i have to comment out the qmake automatic file naming of your translation files from main/main.cpp:
`Q_INIT_RESOURCE(qmake_qmake_qm_files); // qmake names the file`
otherwise it fails with unable to resolve qmake_qmake_qm_files

Regards,
Matt

**Comment by gardenappl** [comment]
+1 for @schmunk42, same issue on Windows 10, qtpass v1.3.2
I'm also commenting here because I believe that issue #520 is related to this.

I don't use Git integration and I don't have native Pass installed.
