### ISSUE TITLE
Display passwords in mono space font

### ISSUE THREAD

**Issue by InnayTool** [IJHack/QtPass#514]
Sometimes is hard to decide if a character in a password is for example an upper case i or an lower case L. So it would be cool if this could be displayed in a mono space font.

**Comment by neilmayhew** [comment]
I see that the changes for this were [reverted][1] recently because they stopped working. However, the problem that this issue identifies is back again. Are there plans to do anything about it?

[1]: https://github.com/IJHack/QtPass/commit/0595f17a71882e8884bfc638642873a44049be66#diff-c72b037f3ac7abbd3d0ee519b6f456013a9bbf5a59df16308939320c04970447

**Comment by neilmayhew** [comment]
It looks to me like `font-family: monospace` could be added to the `setStyleSheet` call at [mainwindow.cpp:1107](https://github.com/IJHack/QtPass/blob/4f4e0c03357acc563f691a82ac4bbecdb08e4eab/src/mainwindow.cpp#L1107).
