### ISSUE TITLE
Copy password by Ctrl+C

### ISSUE THREAD

**Issue by karlgrz** [IJHack/qtpass#60]
I will start by saying how much I am enjoying qtpass, it is a great ui for pass! Thanks for developing it!

It would be great to be able to highlight a password file in the tree and be able to Ctrl+C the password onto the clipboard instead of having to highlight it in the viewer on the right.

Does that make sense?

Again, thanks!

**Comment by annejan** [comment]
Would the "Use clipboard" feature fix this?
![screen shot 2015-06-24 at 19 17 26](https://cloud.githubusercontent.com/assets/294470/8336578/d4216044-1aa5-11e5-97e0-2d42a5158ccc.png)
It has an auto clear option as well..
Just click on the file on the left, and it gets copied to your clipboard, no Ctrl+C needed.

**Comment by karlgrz** [comment]
Thanks for the quick reply!

That would be wonderful...if it worked ;-)

I'm on linux, compiled from source (version 0.8.4).

Using either Native git/gpg or pass, I get the same results. What seems to be happening is it just copies a blank line to the clipboard. The passwords I am trying -do- have the password as the first line. 

I'd be happy to provide more information, or if you have another suggestion.

**Comment by annejan** [comment]
Have just tried on my Arch Linux laptop (KDE as Window Manager) and it works for me.
What window manager are you using?
I would like to have this fail for me too . . so I can fix it.

**Comment by karlgrz** [comment]
Certainly!

I'm on Ubuntu 15.04, using Unity and lightdm.

**Comment by karlgrz** [comment]
Tried this on another machine (my desktop at home) and am seeing the same behavior.

**Comment by annejan** [comment]
Downloading Ubuntu 15 iso to test on a VM.
The main issue is that I'm using the Qt cross-platform clipboard, which apparently is currently broken with Ubuntu. Adding options like Ctrl+C handling won't do a thing since it'll be using the same clipboard API.

I hope to be able to fix this or find a way to be able to patch things upstream, this should affect all Qt applications that use clipboard integration.

Will do some test and might even find a workaround this morning, will keep you updated.

**Comment by annejan** [comment]
I'm getting a warning about the GNOME keyring hijacking the GPG agent, which probably causes the copy and hide functionality to backfire, both using pass and in "native" mode.
![screen shot 2015-06-26 at 11 29 20](https://cloud.githubusercontent.com/assets/294470/8374594/e131641c-1bf6-11e5-85c7-3f9829b9207b.png)
Do you also get this warning?

**Comment by annejan** [comment]
After following the instructions on http://wiki.gnupg.org/GnomeKeyring
Specifically adding `X-GNOME-Autostart-enabled=false` to `~/.config/autostart/gnome-keyring-gpg.desktop` the clipboard integration works again.
![screen shot 2015-06-26 at 11 53 19](https://cloud.githubusercontent.com/assets/294470/8375085/a36d068c-1bfa-11e5-80ec-a4a98448a422.png)
I'll try and add a workaround for QtPass to ignore the warning since this also breaks the "shoulder surfing protection" features.

**Comment by karlgrz** [comment]
@annejan thanks for discovering this! I also get the warnings, but I disregarded them since the CLI worked fine. I will try this out!

**Comment by annejan** [comment]
Well, using the GNOME keyring actually might have some advantages, so I will also (later) make sure that warnings like this don't matter for the overall handling of QtPass.
Since now these warnings also cause passwords to display when you might not want them to.

Changing from GNOME keyring to native GPG Agent got me a different popup for my GPG passphrase for example, so changing keyring is at own risk (but can be re-enabled just as easily).

Thank you for finding this issue, I'll make sure it is fixed for the standard Ubuntu 15.04 (with GNOME keyring enabled) in the next release.

**Comment by karlgrz** [comment]
@annejan adding the config did work, but you're right, now my GNOME keyring caching doesn't enable at startup, so I have to enter my passphrase on every login (I tried rebooting and was prompted again).

That is great news, thank YOU! I'll keep an eye out for the next release.

**Comment by annejan** [comment]
It all seems to work on both Ubuntu and other platforms.
Thanks again for reporting this issue. The current error messages will soon be hide-able in the config.

**Comment by karlgrz** [comment]
Works like a charm, thanks for the quick fix to this!
