### ISSUE TITLE
All text input fields need example text & edit dialogue changes

### ISSUE THREAD

**Issue by lightonflux** [IJHack/qtpass#85]
Just like this:

![bildschirmfoto vom 2015-08-04 02 19 08](https://cloud.githubusercontent.com/assets/1377943/9050555/438680f4-3a4f-11e5-94da-8218fae1324c.png)

----

I assume from the UI: the upper input field is the name of the things i create. And with the button next to it i confirm the action. The create thing then lands in box below.

![bildschirmfoto vom 2015-08-04 02 20 11](https://cloud.githubusercontent.com/assets/1377943/9050565/5aa33156-3a4f-11e5-882f-eadfb94160b3.png)

Okay i know the first is the password, the button is password generation and the last is the secret text input field, or what ever we want to call it. 

Suggestion:

 * *Add password*
 * *Gen.* – short for generate –, *Generate* or dice icon
 * *Write your secrets here*, *Fill me with secrets*, etc.

PS: Owncloud does not use a checkbox, but: 

![bildschirmfoto vom 2015-08-04 02 27 37](https://cloud.githubusercontent.com/assets/1377943/9050661/9398876c-3a50-11e5-83fb-da9238e96b66.png)

**Comment by annejan** [comment]
The example "tips" in the txt fields are a great idea.

There is already some work done to add templating options to the add/edit screen in a separate branch.
For example: login and url
I think they should be displayed as a label + input field per item in the template.

In the `pass` format the password is always the first line, the rest is comments with optional key-value pairs with a colon to separate them.
That is why the password doesn't go to the main text field, since that is just for "comments".
But good to brainstorm a bit about the password field.

Is the "generate password button" really translated to: Erstellen?
That is almost as fun as "Eindrücken" for the git push button . .

**Comment by lightonflux** [comment]
> Is the "generate password button" really translated to: Erstellen?

Yes. That a nice translation bug.

Also see [this beautiful translation](http://www.hyperblog.de/media/users/hoergen/bilder/2008/20081217_altweltraum.png).
