### ISSUE TITLE
When QtPass starts, focus search input box

### ISSUE THREAD

**Issue by rafi** [IJHack/qtpass#89]
Currently when QtPass starts, the `[X]` button is focused.
Instead, please auto-focus the search input box for quicker usage.

**Comment by annejan** [comment]
The weird thing is that in the code I set focus to the lineEdit.
Unfortunately it does in effect focus on the next widget (the clear button) .. which is utterly weird.
If I remove that line it seems that nothing gets focused . . "playing" with this some more until I find a solution, because indeed it should just focus on the input . .

Thanks for noting this (confession I barely use QtPass myself, just for user management, for the rest I use command-line pass) it's a weird bug :)

**Comment by annejan** [comment]
Apparently focussing only works correctly after the app is initialised.
So I made a 10 millisecond one-shot timer to do so. . Works. Will be in 1.0.1
