### ISSUE TITLE
Revoked keys can also open the password store

### ISSUE THREAD

**Issue by wgroenewold** [IJHack/qtpass#94]
Since I'm new to the whole GPG game I don't know if this is a big issue, but I am able to open my Password Store with a revoked key. Furthermore keys that are revoked are also shown as usable keys (see screenshot).

![revoked](https://cloud.githubusercontent.com/assets/2804722/9762849/5b5ada8a-5706-11e5-953f-018aba7f880d.png)

**Comment by annejan** [comment]
Key revocation is weird on GPG . . But I’ll have a look when I got some time.
Might be a simple command to fetch revoked keys from (default) key server.

**Comment by dvarum12** [comment]
By my understanding of revoked keys, this is not a bug. Because then you revoke a key, your are telling others to not use that key, because you have created a new one or it was compromised, but maybe qtpass should offer to re-encrypt all the password (gpg files) with a new gpg-key if the used one is revoked.

**Comment by annejan** [comment]
Yup, that is indeed how revocation works. 
And a nice idea for a feature somewhere allong the way . .
