### ISSUE TITLE
When does the dialog for GPG passkey trigger?

### ISSUE THREAD

**Issue by wgroenewold** [IJHack/qtpass#96]
Hi,

Since I'm new in the whole GPG key-thingie, I was wondering when does the dialog for the passphrase trigger? Because I think it's a good idea to ask again for the passphrase after you closed the application, but somehow this doesn't work this way (so I guess I'm making an obvious thinking mistake). Could you help me clarify this for me?

**Comment by annejan** [comment]
You can choose a timeout and more in your GPG agent settings.
https://www.gnupg.org/documentation/manuals/gnupg/Agent-Configuration.html

This goes across applications that use GPG. 
I personally use a GPG-card that has to be inserted into the laptop (or a USB reader) in order to be able to decrypt, it also requires me to enter a PIN for each decryption event.
